version: '3.7'
services:
    database:
        image: 'postgres:alpine'
        container_name: sf52_starter_postgres
        environment:
            POSTGRES_PASSWORD: main
            POSTGRES_USER: main
            POSTGRES_DB: db_sf52_starter
        ports:
            - '5432'
    redis:
        image: library/redis:6-alpine
        container_name: sf52_starter_redis
        ports: [6379]

    rabbitmq:
        image: library/rabbitmq:3.8-management
        container_name: sf52_starter_mq
        ports: [5672, 15672]

    mailer:
        image: schickling/mailcatcher
        container_name: sf52_starter_mailer
        ports: [ 1025, 1080 ]